FunWithSignalRDI.Web/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FunWithSignalR.Domain.Repository;
using FunWithSignalR.Domain.Model;

namespace FunWithSignalR.Controllers
{ 
    public class BlogPostController : Controller
    {
        private IBlogPostRepository _repository;

        public BlogPostController(IBlogPostRepository repository)
        {
            _repository = repository;
        }

        //
        // GET: /BlogPost/

        public ViewResult Index()
        {
            return View(_repository.GetAllBlogPosts());
        }

        //
        // GET: /BlogPost/Details/5

        public ViewResult Details(int id)
        {
            BlogPost blogpost = _repository.ReadBlogPost(id);
            return View(blogpost);
        }

        //
        // GET: /BlogPost/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /BlogPost/Create

        [HttpPost]
        public ActionResult Create(BlogPost blogpost)
        {
            if (ModelState.IsValid)
            {
                _repository.CreateBlogPost(blogpost);
                return RedirectToAction("Index");  
            }

            return View(blogpost);
        }
        
        //
        // GET: /BlogPost/Edit/5
 
        public ActionResult Edit(int id)
        {
            BlogPost blogpost = _repository.ReadBlogPost(id);
            return View(blogpost);
        }

        //
        // POST: /BlogPost/Edit/5

        [HttpPost]
        public ActionResult Edit(BlogPost blogpost)
        {
            if (ModelState.IsValid)
            {
                _repository.UpdateBlogPost(blogpost);
                return RedirectToAction("Index");
            }
            return View(blogpost);
        }

        //
        // GET: /BlogPost/Review/5

        public ActionResult Review(int id)
        {
            BlogPost blogpost = _repository.ReadBlogPost(id);
            return View(blogpost);
        }

        //
        // POST: /BlogPost/Review/5

        [HttpPost]
        public ActionResult Review(BlogPost blogpost)
        {
            if (ModelState.IsValid)
            {
                _repository.UpdateBlogPost(blogpost);
                return RedirectToAction("Index");
            }
            return View(blogpost);
        }

        //
        // GET: /BlogPost/Delete/5
 
        public ActionResult Delete(int id)
        {
            BlogPost blogpost = _repository.ReadBlogPost(id);
            return View(blogpost);
        }

        //
        // POST: /BlogPost/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            _repository.DeleteBlogPost(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            //db.Dispose();
            base.Dispose(disposing);
        }
    }
}

FunWithSignalRDI.Web/Controllers/DevController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web.Http;
using FunWithSignalR.Domain.Repository;
using FunWithSignalR.Domain.Model;

namespace FunWithSignalRDI.Web.Controllers
{
    public class DevController : ApiController
    {
        IBlogPostRepository _repository;

        public DevController(IBlogPostRepository repository)
        {
            _repository = repository;
        }

        // GET /api/values
        public IEnumerable<BlogPost> Get()
        {
            return _repository.GetAllBlogPosts();
        }

        // GET /api/values/5
        public HttpResponseMessage<BlogPost> Get(int id)
        {
            BlogPost post = _repository.ReadBlogPost(id);
            if (post != null)
            {
                return new HttpResponseMessage<BlogPost>(post, System.Net.HttpStatusCode.OK);
            }
            else
            {
                return new HttpResponseMessage<BlogPost>(null, System.Net.HttpStatusCode.NotFound);
            }
        }

        // POST /api/values
        public HttpResponseMessage Post(BlogPost newPost)
        {
            _repository.CreateBlogPost(newPost);
            return new HttpResponseMessage(System.Net.HttpStatusCode.Created);
        }

        // PUT /api/values/5
        public HttpResponseMessage Put(BlogPost existingPost)
        {
            _repository.UpdateBlogPost(existingPost);
            return new HttpResponseMessage(System.Net.HttpStatusCode.Created);
        }

        // DELETE /api/values/5
        public HttpResponseMessage Delete(int id)
        {
            return new HttpResponseMessage(System.Net.HttpStatusCode.Forbidden);
        }
    }

}

FunWithSignalRDI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FunWithSignalR.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to ASP.NET MVC!";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

FunWithSignalRDI.Web/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace FunWithSignalRDI.Web.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

FunWithSignalRDI.Web/Views/BlogPost/Create.cshtml
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = "Create";
}
<div id="body">
    <section class="content-wrapper main-content clear-fix">
        <div class="content-wrapper">
            <h2>
                Create</h2>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                <fieldset>
                    <legend>BlogPost</legend>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Title)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Title)
                        @Html.ValidationMessageFor(model => model.Title)
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Post)
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.Post, new { rows = 20, cols = 100 })
                        @Html.ValidationMessageFor(model => model.Post)
                    </div>
                    <p>
                        <input type="submit" value="Create" />
                    </p>
                </fieldset>
            }
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </section>
</div>

FunWithSignalRDI.Web/Views/BlogPost/Create.mobile.cshtml
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = "New Post";
}
@section Header {
    @Html.ActionLink("Back", "Index", "Home", null, new { data_icon = "arrow-l", data_rel = "back" })
    <h1>@ViewBag.Title</h1>
}
<div data-role="content">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <ul data-role="listview">
            <li data-role="list-divider">
                @Html.LabelFor(model => model.Title)
            </li>
            <li>
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </li>
            <li data-role="list-divider">
                <div class="editor-label">
                    @Html.LabelFor(model => model.Post)
                </div>
            </li>
            <li>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.Post)
                    @Html.ValidationMessageFor(model => model.Post)
                </div>
            </li>
        </ul>
        <p>
            <input type="submit" value="Create" />
        </p>
    }
</div>

FunWithSignalRDI.Web/Views/BlogPost/Delete.cshtml
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = "Delete";
}
<div id="body">
    <section class="content-wrapper main-content clear-fix">
        <div class="content-wrapper">
            <h2>
                Delete</h2>
            <h3>
                Are you sure you want to delete this?</h3>
            <fieldset>
                <legend>BlogPost</legend>
                <div class="display-label">
                    <h3>
                        Title</h3>
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Title)
                </div>
                <div class="display-label">
                    Post</div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Post)
                </div>
            </fieldset>
            @using (Html.BeginForm())
            {
                <p>
                    <input type="submit" value="Delete" />
                    |
                    @Html.ActionLink("Back to List", "Index")
                </p>
            }
        </div>
    </section>
</div>

FunWithSignalRDI.Web/Views/BlogPost/Delete.mobile.cshtml
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = "Delete";
}
@section Header {
    @Html.ActionLink("Back", "Index", "Home", null, new { data_icon = "arrow-l", data_rel = "back" })
    <h1>@ViewBag.Title</h1>
}
<h3>
    Are you sure you want to delete this?</h3>
<div data-role="content">
    <ul data-role="listview">
        <li data-role="list-divider">
            @Html.DisplayFor(model => model.Title)
        </li>
        <li>
            <pre style="white-space: pre-line">
            @Html.DisplayFor(model => model.Post)
            </pre>
        </li>
    </ul>
</div>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" data-icon="delete" />
    </p>
}

FunWithSignalRDI.Web/Views/BlogPost/Details.cshtml
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = "Details";
}
<div id="body">
    <section class="content-wrapper main-content clear-fix">
        <div class="content-wrapper">
            <h2>
                Details</h2>
            <fieldset>
                <legend>BlogPost</legend>
                <div class="display-label">
                    <h3>
                        Title</h3>
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Title)
                </div>
                <div class="display-label">
                    <h3>
                        Post
                    </h3>
                </div>
                <div class="display-field">
                    <pre style="white-space:pre-line">
                @Html.Encode(Model.Post)
            </pre>
                </div>
            </fieldset>
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                @Html.ActionLink("Back to List", "Index")
            </p>
        </div>
    </section>
</div>

FunWithSignalRDI.Web/Views/BlogPost/Details.mobile.cshtml
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = Model.Title;
}
@section Header {
    @Html.ActionLink("Back", "Index", "Home", null, new { data_icon = "arrow-l", data_rel = "back" })
    <h1>@ViewBag.Title</h1>
}
<div data-role="content">
    <ul data-role="listview">
        <li data-role="list-divider">@Html.DisplayFor(model => model.Title)</li>
        <li>
            <pre style="white-space: pre-line">
                @Html.Encode(Model.Post)
            </pre>
        </li>
    </ul>
</div>
@using (Html.BeginForm("Edit", "BlogPost", new { id = Model.Id }, FormMethod.Get))
{
    <button id="edit" name="edit" data-role="button" data-icon="grid">
        Edit</button>
}
@using (Html.BeginForm("Review", "BlogPost", new { id = Model.Id }, FormMethod.Get))
{
    <button id="review" name="review" data-role="button" data-icon="search">
        Review
    </button>
}
@using (Html.BeginForm("Delete", "BlogPost", new { id = Model.Id }, FormMethod.Get))
{
    <button data-role="button" data-role="button" data-icon="delete">
        Delete
    </button>
}

FunWithSignalRDI.Web/Views/BlogPost/Edit.cshtml
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = "Edit";
}
<div id="body">
    <section class="content-wrapper main-content clear-fix">
        <div class="content-wrapper">
            <h2>
                Edit</h2>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                <fieldset>
                    <legend>BlogPost</legend>
                    @Html.HiddenFor(model => model.Id)
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Title)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Title)
                        @Html.ValidationMessageFor(model => model.Title)
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Post)
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.Post, new { rows = 20, cols = 100 })
                        @Html.ValidationMessageFor(model => model.Post)
                    </div>
                    <p>
                        <input type="submit" value="Save" />
                    </p>
                </fieldset>
            }
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </section>
</div>

FunWithSignalRDI.Web/Views/BlogPost/Edit.mobile.cshtml
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = "Edit";
}
@section Header {
    @Html.ActionLink("Back", "Index", "Home", null, new { data_icon = "arrow-l", data_rel = "back" })
    <h1>@ViewBag.Title</h1>
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div data-role="content">
        <ul data-role="listview">
            <li data-role="list-divider">@Html.LabelFor(model => model.Title)</li>
            <li>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </li>
            <li data-role="list-divider">@Html.LabelFor(model => model.Post)</li>
            <li>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.Post, new { rows = 20, cols = 100 })
                    @Html.ValidationMessageFor(model => model.Post)
                </div>
            </li>
        </ul>
    </div>
    <div>
        <input type="submit" value="Save" />
        <input type="hidden" id="sessinId" value="@Session.SessionID" />
    </div>
}
</div>

FunWithSignalRDI.Web/Views/BlogPost/Index.cshtml
@model IEnumerable<FunWithSignalR.Domain.Model.BlogPost>
<head>
    <meta charset="utf-8" />
    <title>ASP.NET Web API</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
    
</head>
<div id="body">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>
                   Dependeny Injection with ASP.NET</h1>
            </hgroup>
        </div>
    </section>
    <section class="content-wrapper main-content clear-fix">
        @{
            ViewBag.Title = "Dependency Injection with Ninject";
        }
        <h2>
            Existing Posts</h2>
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        @foreach (var item in Model)
        {
            <div class="post-index-item">
                <div class="post-index-title">
                    <strong>
                        @Html.DisplayFor(modelItem => item.Title)
                    </strong>
                </div>
                <div class="post-index-content">
                    @Html.DisplayFor(modelItem => item.Post)
                </div>
                <div class="post-index-footer">
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @*@Html.ActionLink("Review", "Review", new { id = item.Id }) |*@
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </div>
            </div>            
        }
    </section>
</div>

FunWithSignalRDI.Web/Views/BlogPost/Index.iphone.cshtml
@model IEnumerable<FunWithSignalR.Domain.Model.BlogPost>
@{
    ViewBag.Title = "SignalR Fun";
}
@section header
{
    <h1>@ViewBag.Title</h1>
    <div data-role="button" data-icon="plus" class="ui-btn-right">
        @Html.ActionLink("New", "Create")
    </div>
}
<div data-role="content">
    <ul data-role="listview">
        <li data-role="list-divider">Current Posts</li>
        @foreach (var item in Model)
        {
            <li><a href="BlogPost/Details/@item.Id">
                <h3>
                    @item.Title</h3>
                <p>
                    @{
            string val = (item.Post != null) ? 
                                item.Post.Substring(0, item.Post.Length < 100 ? 
                                                        item.Post.Length: 
                                                            100) : 
                         item.Post;
                        @val;
                    }
                </p>
            </a></li>
        }
    </ul>
</div>

FunWithSignalRDI.Web/Views/BlogPost/Index.mobile.cshtml
@model IEnumerable<FunWithSignalR.Domain.Model.BlogPost>
@{
    ViewBag.Title = "DI with Ninject";
}
@section header
{
    <h1>@ViewBag.Title</h1>
    <div data-role="button" data-icon="plus" class="ui-btn-right">
        @Html.ActionLink("New", "Create")
    </div>
}
<div data-role="content">
    <ul data-role="listview">
        <li data-role="list-divider">Current Posts</li>
        @foreach (var item in Model)
        {
            <li>
                @Html.ActionLink(item.Title, "Details", new { id = item.Id })
            </li>    
        }
    </ul>
</div>

FunWithSignalRDI.Web/Views/BlogPost/Review.cshtml
<script src="@Url.Content("~/Scripts/diff_match_patch.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.signalR.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/json2.min.js")" type="text/javascript"></script>
<script type="text/javascript" src="@Url.Content("~/signalr/hubs")"></script>
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = "Review";
}
<div id="body">
    <section class="content-wrapper main-content clear-fix">
        <div class="content-wrapper">
            <h2>
                Review</h2>
            <h4>
                (Share the URL of this post or open it in a new browser. Change in one text and
                watch it change in the other browser)</h4>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                <fieldset>
                    <legend>BlogPost</legend>
                    @Html.HiddenFor(model => model.Id)
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Title)
                        @Html.ValidationMessageFor(model => model.Title)
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.Post, new { rows = 20, cols = 100 })
                        @Html.ValidationMessageFor(model => model.Post)
                    </div>
                    <p>
                        <input type="submit" value="Save" />
                        <br />
                        <input id="sessinId" value="@Session.SessionID" />
                    </p>
                </fieldset>
            }
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">

    $(function () {
        // Proxy created on the fly
        var blog = $.connection.blogHub;
        //Create instance of the diff-match-patch javascript class
        var dmp = new diff_match_patch();

        // Declare a function on the blog hub so the server can invoke it
        blog.addMessage = function (message, sessnId, id) {

            var sessId = $('#sessinId').val();
            var blogId = $('#Id').val();

            if (sessId != sessnId && (blogId == id)) {
                dmp.Match_Distance = 1000;
                dmp.Match_Threshold = 0.5;
                dmp.Patch_DeleteThreshold = 0.5;

                var patches = dmp.patch_make($('#Post').val(), message);
                var results = dmp.patch_apply(patches, $('#Post').val());
                $('#Post').val(results[0]);
            }
        };

        // Start the connection
        $.connection.hub.start();

        $("#Post").keyup(function (event) {
            var sessId = $("#sessinId").val();
            blog.send($("#Post").val(), sessId, $("#Id").val());
        });
    });
</script>

FunWithSignalRDI.Web/Views/BlogPost/Review.mobile.cshtml
<script src="../../Scripts/diff_match_patch.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.signalR.min.js" type="text/javascript"></script>
<script src="../../Scripts/json2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="@Url.Content("~/signalr/hubs")"></script>
@model FunWithSignalR.Domain.Model.BlogPost
@{
    ViewBag.Title = "Review";
}
@section Header {
    @Html.ActionLink("Back", "Index", "Home", null, new { data_icon = "arrow-l", data_rel = "back" })
    <h1>@ViewBag.Title</h1>
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    <div data-role="content">
        <ul data-role="listview">
            <li data-role="list-divider">@Html.LabelFor(model => model.Title)</li>
            <li>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </li>
            <li data-role="list-divider">@Html.LabelFor(model => model.Post)</li>
            <li>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.Post, new { rows = 20, cols = 100 })
                    @Html.ValidationMessageFor(model => model.Post)
                </div>
            </li>
        </ul>
    </div>
    <div>
        <input type="submit" value="Save" />
        <input type="hidden" id="sessinId" value="@Session.SessionID" />
    </div>
}
<script type="text/javascript">

    $(function () {
        // Proxy created on the fly
        var blog = $.connection.blogHub;
        //Create instance of the diff-match-patch javascript class
        var dmp = new diff_match_patch();

        // Declare a function on the blog hub so the server can invoke it
        blog.addMessage = function (message, sessnId, id) {

            var sessId = $('#sessinId').val();
            var blogId = $('#Id').val();

            if (sessId != sessnId && (blogId == id)) {
                dmp.Match_Distance = 1000;
                dmp.Match_Threshold = 0.5;
                dmp.Patch_DeleteThreshold = 0.5;

                var patches = dmp.patch_make($('#Post').val(), message);
                var results = dmp.patch_apply(patches, $('#Post').val());
                $('#Post').val(results[0]);
            }
        };

        // Start the connection
        $.connection.hub.start();

        $("#Post").keyup(function (event) {
            var sessId = $("#sessinId").val();
            blog.send($("#Post").val(), sessId, $("#Id").val());
        });
    });
</script>

FunWithSignalRDI.Web/Views/Home/Index_OLD.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>ASP.NET Web API</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <header>
        <div class="content-wrapper">       
            <div class="float-left">
                <p class="site-title"><a href="/">ASP.NET Web API</a></p>
            </div>
        </div>
    </header>
    <div id="body">
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>Welcome to ASP.NET Web API!</h1>
                    <h2>Modify the code in this template to jump-start your ASP.NET Web API development.</h2>
                </hgroup>
                <p>
                    ASP.NET Web API allows you to expose your applications, data and services to the web directly over HTTP. 
                </p>
                <p>
                    To learn more about ASP.NET Web API visit <a href="http://go.microsoft.com/fwlink/?LinkID=238195" title="ASP.NET Web API Website">http://asp.net/web-api</a>. 
                    The page features <span class="highlight">videos, tutorials, and samples</span> to help you get the most from 
                    ASP.NET Web API. If you have any questions about ASP.NET Web API, visit 
                    <a href="http://go.microsoft.com/fwlink/?LinkID=238196" title="ASP.NET Web API Forum">our forums</a>.
                </p>
            </div>
        </section>
        <section class="content-wrapper main-content clear-fix">
            <h3>We suggest the following steps:</h3>
            <ol class="round">
                <li class="one">
                    <h5>Name your Web API</h5>
                    Requests are routed to Web APIs based on their name. The Web API in this template will respond to requests
                    sent to <code>/api/values</code>, but you can change this by renaming the <code>ValuesController</code> type. 
                    Your Web API name should end with <code>Controller</code>. 
                </li>
                <li class="two">
                    <h5>Implement your Web API actions</h5>
                    By convention, Web API actions map directly to HTTP methods, like GET, POST, PUT, and DELETE. To handle a 
                    given HTTP method just prefix your action name with the HTTP method you want to handle. Action parameters 
                    are bound to data from the request through model binding. Data returned from an action is formatted in the 
                    response as JSON or XML as requested by the client.
                </li>
                <li class="three">
                    <h5>Add Web APIs and routes</h5>
                    Add additional Web APIs using the Add New Item dialog. You can also fully control the URI space for your 
                    Web APIs in Global.asax by adding routes to the <code>HttpConfiguration</code> object passed to the 
                    <code>RegisterApis</code> method.
                </li>
            </ol>

            <section class="features">
                <section class="feature">
                    <img src="@Url.Content("~/Images/aspNetHome.png")" alt="ASP.NET Home" />
                    <h3>Home of ASP.NET</h3>
                    <p>
                        ASP.NET is a free, fully supported Web application framework that helps you create standards-based web solutions. 
                        Whether you're new to ASP.NET or an experienced developer, the <a href="http://asp.net">ASP.NET website</a> 
                        is your source for news, training, downloads, and support.
                    </p>
                </section>
                <section class="feature">
                    <img src="@Url.Content("~/Images/NuGetGallery.png")" alt="NuGet Gallery" />
                    <h3>NuGet Gallery</h3>
                    <p>
                        NuGet is a Visual Studio extension that makes it easy to install and update open source libraries and tools in 
                        Visual Studio. To see available packages, visit the <a href="http://nuget.org">NuGet gallery</a>.
                        You can also develop your own package and share it in the gallery.
                    </p>
                </section>
                <section class="feature">
                    <img src="@Url.Content("~/Images/findHosting.png")" alt="Find Hosting" />
                    <h3>Find Web Hosting</h3>
                    <p>
                        You can easily find a web hosting company that offers the right mix of features and price for your applications. 
                        Visit <a href="http://microsoft.com/web/hosting" title="Microsoft/Web Website">Microsoft.com/web</a> to 
                        explore offerings from many providers.
                    </p>
                </section>
            </section>
        </section>
    </div>
</body>
</html>

FunWithSignalRDI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css")" rel="stylesheet" type="text/css" />
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")" rel="stylesheet" type="text/css" />
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Scripts/js")"></script>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <header>
        @Html.Partial("_ViewSwitcher")
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="/">Dependeny Injection using Ninject IoC Container</a></p>
            </div>
        </div>
    </header>
    <div>
        @RenderBody()
    </div>
</body>
</html>

FunWithSignalRDI.Web/Views/Shared/_ViewSwitcher.cshtml
@*Request.Browser.IsMobileDevice &&*@
@if ( Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}